# Generated by Django 4.2.3 on 2023-07-18 18:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='cooks',
            field=models.ManyToManyField(related_name='cooks', to=settings.AUTH_USER_MODEL),
        ),
    ]
